export const ROLES = {
  STUDENT: "STUDENT",
  ORGANIZER: "ORGANIZER",
  VOLUNTEER: "VOLUNTEER",
  ADMIN: "ADMIN",
};

export const EVENT_STATUSES = {
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  LIVE: "LIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const REGISTRATION_STATUSES = {
  CONFIRMED: "CONFIRMED",
  WAITLISTED: "WAITLISTED",
  CANCELLED: "CANCELLED",
  CHECKED_IN: "CHECKED_IN",
  NO_SHOW: "NO_SHOW",
};
